demo:
  outputs:
    dev:
      account: eagsaki-wlb31127
      database: DBT_DEMO
      user: Nagaraj047
      password: Nagaraju@047
      role: ACCOUNTADMIN
      schema: DBT_PROJECT
      threads: 1
      type: snowflake
      warehouse: COMPUTE_WH
  target: dev